# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven and Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  setup_pipeline:
    name: Setup Pipeline
    #needs: commit_at
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      #### ---- Maven Clean ----
      - name: Maven Clean
        run: mvn clean
      #### ---- Maven Compile ----
      - name: Maven Compile
        run: mvn compile
      #### ---- Gradle Clean ----
      - name: Gradle Clean
        run: sh ./gradlew clean
      #### ---- Gradle Assemble ----
      - name: Gradle Assemble
        run: sh ./gradlew assemble

  test:
    name: Test
    needs: setup_pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      #### ---- Maven Test ----
      - name: Maven Test
        run: mvn test
      #### ---- Gradle Test ----
      - name: Gradle Test
        run: sh ./gradlew test

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      #### ---- Maven Build and Upload Artifact Built by Maven ----
      - name: Maven Package
        run: mvn -B package --file pom.xml
      - name: Make 'target/libs' directory to store Maven Artifact
        run: mkdir target/libs
      - name: Copy Files for Maven Artifact
        run: cp target/*.jar target/libs
      - uses: actions/upload-artifact@v1
        with:
          name: JSON-java-maven
          path: target/libs
      - name: Delete  'target/libs' directory
        run: rm -rf target/libs
      #### ---- Gradle Build and Upload Artifact Built by Gradle ----
      - name: Gradle Build
        run: sh ./gradlew build
      - uses: actions/upload-artifact@v1
        with:
          name: JSON-java-gradle
          path: build/libs

 # Deploy Script Comes here
    #- name: Publish to GitHub Packages Apache Maven
    #  run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
    #  env:
    #    GITHUB_TOKEN: ${{ github.token }}

