# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  maven_compile:
    name: Setup
    #needs: commit_at
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    ## Maven Compile
    - name: Compile with Maven
      run: mvn compile
  maven_test:
    name: Maven Test
    needs: maven_compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    ## Maven Test
    - name: Test with Maven
      run: mvn test
  maven_build:
    name: Maven Build
    needs: maven_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    ## Maven Build
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - uses: actions/upload-artifact@v1
      with:
        name: JSON-java-maven
        path: build/libs
  gradle_assemble:
    name: Gradle Assemble
    needs: maven_build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    ## Gradle Assemble
    - name: Assemble with Gradle
      run: sh ./gradlew assemble
  gradle_check:
    name: Gradle Check
    needs: gradle_assemble
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    ## Gradle Check
    - name: Gradle Check, Gradle Test is inclusive
      run: sh ./gradlew check
  gradle_build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    ## Gradle Build
    - name: Build with Gradle
      run: sh ./gradlew build
    - uses: actions/upload-artifact@v1
      with:
        name: JSON-java-gradle
        path: build/libs

 # Deploy Script Comes here
    #- name: Publish to GitHub Packages Apache Maven
    #  run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
    #  env:
    #    GITHUB_TOKEN: ${{ github.token }}

